name: Trace
description: Cryptocurrency portfolio and market explorer.
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  circular_chart_flutter : ^0.0.2
  url_launcher: 6.1.6
  http: ^0.12.0
  package_info:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
